version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: alloy-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: alloy_canvas

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: alloy-backend

    restart: always

    ports:
      - "5000:5000"

    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:5432/alloy_canvas

      JWT_SECRET: supersecret

      PORT: 5000

    depends_on:
      - postgres

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend

    container_name: alloy-frontend

    restart: always

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:5000

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
